config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :animals
end

#      Prefix Verb   URI Pattern                 Controller#Action
#     animals GET    /animals(.:format)          animals#index
#             POST   /animals(.:format)          animals#create
#  new_animal GET    /animals/new(.:format)      animals#new
# edit_animal GET    /animals/:id/edit(.:format) animals#edit
#      animal GET    /animals/:id(.:format)      animals#show
#             PATCH  /animals/:id(.:format)      animals#update
#             PUT    /animals/:id(.:format)      animals#update
#             DELETE /animals/:id(.:format)      animals#destroy

app/models/animal.rb
class Animal < ApplicationRecord
  CATEGORIES = %w(cat dog fish rat fox)
  validates :name, presence: true
  validates :category, inclusion: { in: CATEGORIES }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController

before_action :set_animal, only: [:show, :edit, :update, :destroy]

  def index
    @animals = Animal.all
  end
  def show
  end
  def new
    @animal = Animal.new
  end
  def create
    Animal.create(animal_params)
    redirect_to animals_path
  end
  def edit

  end
  def update
    @animal.update(animal_params)
    redirect_to animals_path
  end
  def destroy
    @animal.destroy
    redirect_to animals_path
  end

private
  def set_animal
    @animal = Animal.find(params[:id])
  end
  def animal_params
    params.require(:animal).permit(:name, :category, :found_at)
  end

end

#      Prefix Verb   URI Pattern                 Controller#Action
#     animals GET    /animals(.:format)          animals#index
#             POST   /animals(.:format)          animals#create
#  new_animal GET    /animals/new(.:format)      animals#new
# edit_animal GET    /animals/:id/edit(.:format) animals#edit
#      animal GET    /animals/:id(.:format)      animals#show
#             PATCH  /animals/:id(.:format)      animals#update
#             PUT    /animals/:id(.:format)      animals#update
#             DELETE /animals/:id(.:format)      animals#destroy

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-6 col-sm-offset-3">
      <%= simple_form_for @animal do |a| %>


        <%= a.input :name, label: "Thingy", placeholder: "Cat", label_html: {class: "badge badge-default"} %>
        <%= a.input :category, label: false, collection: Animal::CATEGORIES, prompt: "choose one", input_html: {class: "input-lg"} %>
        <%= a.input :found_at, as: :string, placeholder: "16/08/2016", input_html: {id: "found-datepicker"} %>

      <%= a.submit "Go", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/animals/edit.html.erb
<h1 class="text-center">Edit kitty's info</h1>

<%= render "form" %>

app/views/animals/index.html.erb
<h2 class="text-center">Lost Kittens</h2>

<div class="container">
<div class="row">
<% @animals.each do |animal| %>

<div class="col-xs-12 col-sm-6 col-md-3">
<h2><%= animal.name %></h2>
<h3><%= animal.category %></h3>
<h2><%= animal.found_at %></h3>
<%= link_to "checkit", animal_path(animal), class: "btn btn-primary" %>
<%= link_to "edit", edit_animal_path(animal), class: "btn btn-primary" %>
<%= link_to "kill it", animal_path(animal), method: :delete, class: "btn btn-primary" %>
</div>
<% end %>
</div>
</div>

app/views/animals/new.html.erb
<h1 class="text-center">You've found a kitty</h1>

<%= render "form" %>

app/views/animals/show.html.erb
<h3><%= @animal.name %></h3>
<h3><%= @animal.category %></h3>
<h2><%= @animal.found_at %></h3>
<%= link_to "see all", animals_path %>
<%= link_to "edit", edit_animal_path(@animal) %>
<%= link_to "kill it", animal_path(@animal), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Lostkitty</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>